import { describe, expect, it } from "vitest";
import { matchReferenceOf, parseMatchReference, type MatchReference } from "@/explain/matchRef";
import { sampleFixture } from "@/match/fixture";
import { generateMatch } from "@/simulation/generate";
import { DEFAULT_DRAFT, controlsOf, tacticsFromControls } from "@/components/setup";
import { resolveMatch } from "@/server/resolveMatch";

const roundTrip = (ref: MatchReference) => parseMatchReference(JSON.parse(JSON.stringify(ref)));

describe("match references", () => {
  it("names the scripted demo and resolves it to the built-in fixture", () => {
    const ref = matchReferenceOf(sampleFixture, sampleFixture.matchId)!;
    expect(ref).toEqual({ kind: "sample", matchId: sampleFixture.matchId });
    const parsed = roundTrip(ref);
    expect(parsed.ok).toBe(true);
    const resolved = resolveMatch(ref);
    expect(resolved.ok && resolved.fixture).toBe(sampleFixture);
  });

  it("rebuilds a match generated by the set-up drawer, formation change included", () => {
    const draft = structuredClone(DEFAULT_DRAFT);
    draft.seed = "1234";
    draft.durationSeconds = 30;
    draft.teams.home.formation = "4-4-2";
    draft.changeOn.away = true;
    draft.teams.away.changeAt = "12.5";
    draft.teams.away.changeTo = "4-2-3-1";
    const browser = generateMatch({ seed: 1234, durationMs: 30_000, tactics: tacticsFromControls(controlsOf(draft), 30) });

    const ref = matchReferenceOf(browser, sampleFixture.matchId)!;
    expect(ref).toMatchObject({ kind: "generated", seed: 1234, durationMs: 30_000 });
    const parsed = roundTrip(ref);
    if (!parsed.ok) throw new Error(parsed.error);
    const resolved = resolveMatch(parsed.reference);
    if (!resolved.ok) throw new Error(resolved.error);
    expect(resolved.fixture.matchId).toBe(browser.matchId);
    expect(resolved.fixture.events).toEqual(browser.events);
    expect(resolved.fixture.snapshots.length).toBe(browser.snapshots.length);
  });

  it("refuses a recipe that does not reproduce the claimed matchId", () => {
    const fixture = generateMatch({ seed: 7, durationMs: 20_000 });
    const ref = matchReferenceOf(fixture, sampleFixture.matchId)!;
    if (ref.kind !== "generated") throw new Error("expected generated");
    expect(resolveMatch({ ...ref, seed: 8 }).ok).toBe(false);
    expect(resolveMatch({ ...ref, tactics: { ...ref.tactics, home: { formation: "4-4-2", changes: [] } } }).ok).toBe(false);
    expect(resolveMatch({ kind: "sample", matchId: "something-else" }).ok).toBe(false);
  });

  it("has no reference for a fixture it cannot rebuild", () => {
    const { generator: _g, ...older } = generateMatch({ seed: 3, durationMs: 10_000 });
    expect(matchReferenceOf(older as typeof sampleFixture, sampleFixture.matchId)).toBeNull();
  });

  it("rejects malformed or out-of-range references", () => {
    const good = {
      kind: "generated",
      matchId: "sim-v4-1-10000-abc",
      seed: 1,
      durationMs: 10_000,
      tactics: { home: { formation: "4-3-3", changes: [] }, away: { formation: "4-4-2", changes: [{ t: 5_000, formation: "4-3-3" }] } },
    };
    expect(parseMatchReference(good).ok).toBe(true);
    const bad = (change: (r: Record<string, any>) => void) => {
      const copy = structuredClone(good) as Record<string, any>;
      change(copy);
      return parseMatchReference(copy).ok;
    };
    expect(bad((r) => (r.extra = 1))).toBe(false);
    expect(bad((r) => (r.fixture = {}))).toBe(false);
    expect(bad((r) => (r.kind = "upload"))).toBe(false);
    expect(bad((r) => (r.matchId = "a b"))).toBe(false);
    expect(bad((r) => (r.seed = -1))).toBe(false);
    expect(bad((r) => (r.seed = 1.5))).toBe(false);
    expect(bad((r) => (r.durationMs = 500_000))).toBe(false);
    expect(bad((r) => (r.durationMs = 10_050))).toBe(false);
    expect(bad((r) => (r.tactics.home.formation = "3-5-2"))).toBe(false);
    expect(bad((r) => (r.tactics.away.changes[0].t = 10_000))).toBe(false);
    expect(bad((r) => (r.tactics.away.changes = Array.from({ length: 4 }, (_, i) => ({ t: 1_000 + i, formation: "4-3-3" }))))).toBe(false);
    expect(bad((r) => delete r.tactics.home.changes)).toBe(false);
    expect(parseMatchReference(null).ok).toBe(false);
    expect(parseMatchReference({ kind: "sample", matchId: "x", extra: true }).ok).toBe(false);
  });
});
